--- !ruby/object:Jumpstart::Configuration
application_name: Nestor Planchet
business_name: SAS Nestor Planchet
business_address: 2 place Antonin Jutard 69003 Lyon
domain: example.com
support_email: contact@nestor.ai
default_from_email: Jumpstart <support@example.com>
background_job_processor: async
email_provider: ''
personal_accounts: true
register_with_account: false
collect_billing_address: false
apns: false
fcm: false
integrations:
omniauth_providers:
- google-oauth2
payment_processors:
multitenancy:
gems:
